[tool.poetry]
name = "validate-ingestion"
version = "2.0.0"
description = "Lambda step: validate ingested data"
authors = ["Amazon Web Services"]
package-mode = false
packages = []

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
boto3 = "1.28.57"
aws-lambda-powertools = "3.31.1"

[tool.poetry.group.test.dependencies]
pytest = "7.4.0"
pytest-cov = "6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
